version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql-estagflix
    volumes:
      - mysqldb-dev:/var/lib/mysql
    restart: always
    env_file: .env-dev
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    networks:
      rede:
        ipv4_address: 10.5.0.6
    ports:
      - "3306:3306"
  web:
    build:
      context: .
    container_name: estagflix
    restart: always
    env_file: .env-dev
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
    networks:
      rede:
        ipv4_address: 10.5.0.5
    ports:
      - "8000:80"
volumes:
  mysqldb-dev:

networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1





#networks:
#  estagflix-lan:
#    driver: bridge
