version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql-estagflix
    volumes:
      - mysqldb-dev:/var/lib/mysql
    restart: always
    env_file: .env-dev
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - "3000:3306"
  web:
    build:
      context: .
    container_name: estagflix
    restart: always
    env_file: .env-dev
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "8000:80"

volumes:
  mysqldb-dev:
