version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql-estagflix${ENV:--prod}
    volumes:
      - mysqldb:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    networks:
      - estagflix-lan
    ports:
      - "${MYSQL_PORT:-3000}:3306"

  web:
    build:
      context: .
    container_name: estagflix${ENV:--prod}
    restart: always
    networks:
      - estagflix-lan
    environment: 
      HOST_MYSQL: "mysql-estagflix${ENV:--prod}"
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
    ports:
      - "${WEB_PORT:-80}:80"

networks:
  estagflix-lan:
    driver: bridge

volumes:
  mysqldb:
